language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: J5Ykr/zgFSytIq55x+OcVUCxwv9IkmOB79N7TuzQliFBT6QR4MtSv9FKzONwWugWvEBVQXZ4OLeKwPLlr9/kLg/4EoPsMaVEixq1NM9kBWDAWMraOkcoZxHhHbrUgnQ6A3IONC60ZGIPSbPjM5GEy0ONXl2fXSPrvk6B6kfYdofwuoIbfUz7+WAgBTBZN63ibs0aMAKD1GwWuXI9K8Ispd4t32IjG7CY3KElidP+GrMrZJeCR7VM9QqiM4dQWp+TpDiD8myaKXIgcf8I1RtlyD5H7gK0Q46qdmVs0VDs83KWL7msI+b427V4rdQexCGEduVHcDMlWBGaxMkgLpP/eLpMIlvWxsd3zCN9F7oBlo7LAkATDDx5pHMXeNIeU5uXBLbiiUwSPjlJO6OXLLdlgNRcnpimpOkxgWQIeCgNMC2122plhz8UhODrEVzMh6/aDMhlazwbIdWljeBiVYYoDzBfwRzwYMWpcccGCEyD7VsoeNGWbvrwqCDTvRcthK1ddss45iEX4pAHlp2fEjvXUhJ6LdPTvd+Q5P3qFYFO5FrMdSnGxOvNJ1uQ7V3vR8VO8sKO/TqhtyyUr7YbmqHd6WapFaFZsXrdIcptPg6wxwgXD9UHxH7P9BV8GbShp9pGVYoNRm0RAGpbU2lGCNCdeQX45wGjyfTxkyqmVz2Buo8=
  app: somuchnews
  on:
    repo: responderi/Fake-News
