language: java
jdk:
- oraclejdk8
deploy:
  api_key:
    secure: swk6QdSVT3t279Qz0Y562IkFwreqYwITfYFFCMSX+Ne5a02dpw5I9+oipIhYsI3yoatYHgypnBLIWJQevgqquBqUuwlalJdL6Mi4ZxkbLX9r457b4hxw8I6kU86ndi7XIyBnfrZQE6YKhwIyFAOOm5kjbGCFyMsLRddcSVVrrLXio9+Hc0Ogz9e6qWZmFNNtyirIXUF0q5mRns+BxHaN2uqrNufConc97k5JdZvtFHPOgFPeShAIof0QVveOfXJRTYFsU7FnLRBu997YqLMpZLxNa9gRL/CL5ZGtDiv7LvZh3taXG0rVB0N912ufbv7Dxo6QiHrnoIhP4YxYuzpf8QJcs+0EFAoGOLmJJGa/1/WhdbqWPv3ypTp+J8PybqXA7937UDRaYB1vfslajKuO2PAU/83FtDG9HX9s7nIsOTJJZlIzFHxMPtEHuX6taJzA2DAKq4TcWECBFE6nFMc1OcJttC+H9iupMIlv/Ai2y4R6+QquSYwtwrIbQGPU0h6jJ1yxo7keBFNtZ9ja7WcAHFUTwVQes6kkTzoCznkQ8+iRCQE28HsfbF1S+mFJxx8mv26z1doW/ZuEvx4E3y0VI3h0peGVOjlCGj2f3nrdFWKEMN91XfLm2yGuOTq1cQ+j92Xgy68+5M6dm2xHrTOSO5Le5EBGptvOmRAZRRZbITg=
